### ISSUE TITLE
Feature Request: Variable Column Height

### ISSUE THREAD

**Issue by brian6932** [ioriayane/Hagoromo#112]
Currently, you can adjust the width of a column, it would also be nice to adjust their heights to stack columns. Alternatively, there could be a page feature.

**Comment by ioriayane** [comment]
Thank you for your request.
However, I could not visualize the finished product.
Can you make a simple diagram of the finished product you have?

**Comment by brian6932** [comment]
Something like this I guess
1. Variable column height
![](https://github.com/ioriayane/Hagoromo/assets/18603393/3bae6e93-4c9e-429c-9cff-dce22a1ffd4b)
	- Column settings
	![](https://github.com/ioriayane/Hagoromo/assets/18603393/24881af9-6aa6-4ebe-a03c-5652d290ffaa)
	
1. Pages
![](https://github.com/ioriayane/Hagoromo/assets/18603393/006192db-e620-4c3b-a612-7ed97185f8f6)

**Comment by ioriayane** [comment]
Thanks for creating a good diagram.
I see.

1. About the variable column height
It might be less efficient if there are fewer columns to display on the bottom row.
But it is interesting because it seems to work well on vertical monitors as well as simply large monitors.

2. About pages
It might be less effective because the number of columns that can be seen at the same time is not that different from now.
You can still use Ctrl+Left/Right or number keys to move the columns you want to see.
For example, it might be a good idea to update Ctrl+PageUp/Down to scroll the visible area like paging.

**Comment by brian6932** [comment]
> 2\. You can still use Ctrl+Left/Right or number keys to move the columns you want to see.

Oh cool, didn't know you could do that

**Comment by ioriayane** [comment]
I have released it so please try it.

**Comment by brian6932** [comment]
How does it work?
